// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVU8DSjoUtp4-q0UX1YnKn_mnEX0HSoi0',
    appId: '1:214471292920:web:4aa239025cf37ec960080d',
    messagingSenderId: '214471292920',
    projectId: 'wallora-a79f9',
    authDomain: 'wallora-a79f9.firebaseapp.com',
    storageBucket: 'wallora-a79f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bSd8c_bJHLFrLViY6X-xwEWGkiY-FeM',
    appId: '1:214471292920:android:21183af81f9cfe5360080d',
    messagingSenderId: '214471292920',
    projectId: 'wallora-a79f9',
    storageBucket: 'wallora-a79f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7I5cqJMUwriRyZMOw94-k-17JNci_og',
    appId: '1:214471292920:ios:f241a13203ad14b160080d',
    messagingSenderId: '214471292920',
    projectId: 'wallora-a79f9',
    storageBucket: 'wallora-a79f9.firebasestorage.app',
    iosBundleId: 'com.example.wallora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj7I5cqJMUwriRyZMOw94-k-17JNci_og',
    appId: '1:214471292920:ios:f241a13203ad14b160080d',
    messagingSenderId: '214471292920',
    projectId: 'wallora-a79f9',
    storageBucket: 'wallora-a79f9.firebasestorage.app',
    iosBundleId: 'com.example.wallora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVU8DSjoUtp4-q0UX1YnKn_mnEX0HSoi0',
    appId: '1:214471292920:web:116faf5a6098d58260080d',
    messagingSenderId: '214471292920',
    projectId: 'wallora-a79f9',
    authDomain: 'wallora-a79f9.firebaseapp.com',
    storageBucket: 'wallora-a79f9.firebasestorage.app',
  );
}
